project:
  type: website
  output-dir: docs

website:
  title: "RNA-Seq analysis"
  repo-url: https://github.com/mcic-osu/rnaseq-intro
  repo-actions: [edit, issue]
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    background: "#666666"
    search: true
    left:
      - href: index.qmd
        text: "{{< fa home >}}"
      - href: modules/intro.qmd
        text: Introduction
      - sidebar:computing_skills
      - sidebar:reads_to_counts
      - sidebar:count_analysis
    right:
      - text: Reference material
        menu:
          - text: Specific tutorials
          - href: info/osc_transfer.qmd
            text: "- File transfer to and from OSC"
          - href: info/osc_ssh.qmd
            text: "- Connecting to OSC with SSH"
          - text: General info
          - href: info/shell_commands.qmd
            text: "- Shell commands overview"
          - href: info/shell_shortcuts.qmd
            text: "- Shell keyboard shortcuts"
          - text: "- Further Resources"
          - text: "- Glossary"
      - href: info/about.qmd
        text: About
      - icon: github
        href: https://github.com/mcic-osu/rnaseq-intro
  sidebar:
      - id: computing_skills
        title: A. Computing Skills
        style: docked
        background: light
        collapse-level: 2
        contents:
          - href: modules/A01_osc.qmd
            text: "A1. OSC"
          - href: "modules/A02_vscode.qmd"
            text: "A2. VS Code"
          - href: "modules/A03_shell1.qmd"
            text: "A3. Unix shell I"
          - href: "modules/A04_shell2.qmd"
            text: "A4. Unix shell II"
          - href: "modules/A05_fastq.qmd"
            text: "A5. FASTQ files"
          - href: "modules/A06_ref-files.qmd"
            text: "A6. Reference genome files"
          - href: "modules/A07_overview.qmd"
            text: "A7. Next steps, variables & loops"
          - href: "modules/A08_scripts.qmd"
            text: "A8. Shell scripting"
          - href: "modules/A09_software.qmd"
            text: "A9. Software at OSC"
          - href: "modules/A10_slurm.qmd"
            text: "A10. SLURM batch jobs"
      - id: reads_to_counts
        title: "B. From reads to counts"
        style: docked
        background: light
        collapse-level: 2
        contents:
          - href: "modules/B01_fastqc.qmd"
            text: "B1. Read QC with _FastQC_"
          - href: "modules/B03_trimgalore.qmd"
            text: "B2. Trimming with _TrimGalore_"
      - id: count_analysis
        title: "C. Count table analysis"
        style: docked
        background: light
        collapse-level: 2
        contents:
          - href: "modules/C01_DE.qmd"
            text: "C1. Count table analysis"
  page-footer:
    left: "2023-2024, Jelmer Poelstra"
    right:
      - icon: github
        href: https://github.com/mcic-osu/rnaseq-intro

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      body-width: 750px

execute:
  freeze: auto
